name: tt_1
description: Travel Time Release 1

version: 1.0.1+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.13
  provider: ^6.0.0
  intl: ^0.17.0
  flutter_typeahead: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.2

flutter:
  assets:
    - lib/assets/dollar.png
    - lib/assets/scale.jpg
    - lib/assets/gaspump.jpg
    - lib/assets/exchange.png
    - lib/assets/travel.jpg
    - lib/assets/tape.jpg
    - lib/assets/measures.png
    - lib/assets/thermometer.jpg
    - lib/assets/shoesize.png
    - lib/assets/volume.jpg
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/travel.jpg"
